#!/usr/bin/env python3
"""Generate the AMap classic lineType contract from the official JS runtime."""

import argparse
import hashlib
import re
from pathlib import Path


FUNCTION = re.compile(
    r"function getLineTypeStyle\(t\)\{switch\(t\)\{(?P<body>.*?)\}\}"
)
CLAUSE = re.compile(
    r"(?P<cases>(?:case \d+:)+|default:)return\"(?P<style>[^\"]+)\";?"
)


def parse_style(value: str):
    cap = "LineCap::Butt"
    if value.endswith("_roundcap"):
        cap = "LineCap::Round"
        value = value.removesuffix("_roundcap")
    elif value.endswith("_squarecap"):
        cap = "LineCap::Square"
        value = value.removesuffix("_squarecap")
    if value.startswith("railway("):
        value = "dash" + value[len("railway"):]
    if value == "solid":
        return [0, 0, 0, 0], 0, cap
    match = re.fullmatch(r"dash\((\d+(?:,\d+){1,3})\)", value)
    if not match:
        raise ValueError(f"unsupported official line type style: {value}")
    lengths = [int(item) for item in match.group(1).split(",")]
    if len(lengths) not in (2, 4):
        raise ValueError(f"unsupported dash length count: {value}")
    return lengths + [0] * (4 - len(lengths)), len(lengths), cap


def generate(runtime: Path) -> str:
    data = runtime.read_bytes()
    source = data.decode("utf-8", errors="ignore")
    matches = list(FUNCTION.finditer(source))
    if len(matches) != 1:
        raise ValueError(
            f"official getLineTypeStyle contract must match once, got {len(matches)}"
        )
    records = []
    default = None
    consumed = ""
    for clause in CLAUSE.finditer(matches[0].group("body")):
        consumed += clause.group(0)
        pattern = parse_style(clause.group("style"))
        cases = [int(value) for value in re.findall(r"case (\d+):", clause.group("cases"))]
        if cases:
            records.extend((case, pattern) for case in cases)
        else:
            default = pattern
    compact_body = matches[0].group("body").replace(";", "")
    if consumed.replace(";", "") != compact_body:
        raise ValueError("unparsed tokens in official getLineTypeStyle contract")
    if default is None:
        raise ValueError("official getLineTypeStyle default is missing")

    def row(line_type, pattern):
        lengths, count, cap = pattern
        return (
            f"    {{{line_type}, {{{{{lengths[0]}, {lengths[1]}, "
            f"{lengths[2]}, {lengths[3]}}}}}, {count}, {cap}}},"
        )

    digest = hashlib.sha256(data).hexdigest()
    lines = [
        "// Generated by scaffold/tools/generate_amap_line_type_data.py.",
        f"// Source SHA256: {digest}; official getLineTypeStyle().",
        "// Do not edit manually.",
        "",
        "static constexpr LineTypeRecord kOfficialLineTypes[] = {",
    ]
    lines.extend(row(line_type, pattern) for line_type, pattern in records)
    lines.extend([
        "};",
        "",
        "static constexpr LineTypeRecord kOfficialUnknownLineType =",
        "    " + row(-1, default).strip().removesuffix(",") + ";",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("runtime", type=Path)
    parser.add_argument("-o", "--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.runtime))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
