#!/usr/bin/env python3
"""Generate surface/building tables from an official AMap style PBF."""

import argparse
import hashlib
from pathlib import Path

from extract_amap_style import extract


def argb(value):
    if not value or not value.startswith("#") or len(value) != 9:
        raise RuntimeError(f"invalid official ARGB color: {value}")
    return f"0x{value[1:].upper()}u"


def emit_surfaces(styles):
    grouped = {}
    for class_code in sorted(map(int, styles)):
        for record in styles[str(class_code)]:
            color = record.get("surfaceFillColor")
            # The provider PBF currently contains a few reversed windows
            # (minZoom > maxZoom).  They select no display zoom in the
            # official window contract, so keep them out of the executable
            # table instead of relying on incidental Step stop ordering to
            # make them invisible.
            if (color is not None and
                    record["minZoom"] <= record["maxZoom"]):
                grouped.setdefault((class_code, record["subKey"]), []).append(
                    (record["minZoom"], record["maxZoom"], argb(color)))
    normalized = []
    for (class_code, sub_key), records in sorted(grouped.items()):
        merged = []
        for minimum, maximum, color in sorted(records):
            if merged and minimum <= merged[-1][1]:
                if color != merged[-1][2]:
                    raise RuntimeError(
                        "overlapping official surface contracts disagree: "
                        f"{class_code}:{sub_key} {merged[-1]} vs "
                        f"{(minimum, maximum, color)}")
                merged[-1] = (merged[-1][0],
                              max(merged[-1][1], maximum), color)
            else:
                merged.append((minimum, maximum, color))
        normalized.extend((class_code, sub_key, minimum, maximum, color)
                          for minimum, maximum, color in merged)
    rows = [f"    {{{class_code}, {sub_key}, {minimum}, {maximum}, "
            f"{color}}},"
            for class_code, sub_key, minimum, maximum, color in normalized]
    return "\n".join([
        "static constexpr SurfaceRecord kOfficialSurfaceRecords[] = {",
        *rows, "};"])


def emit_buildings(styles):
    rows = []
    for record in styles["55001"]:
        roof = record.get("roofColor")
        wall = record.get("wallColor")
        if (roof is not None and wall is not None and
                record["minZoom"] <= record["maxZoom"]):
            rows.append(f"    {{{record['subKey']}, {record['minZoom']}, "
                        f"{record['maxZoom']}, {argb(roof)}, {argb(wall)}}},")
    return "\n".join([
        "static constexpr BuildingRecord kBuilding55001[] = {",
        *rows, "};"])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("pbf", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    args = parser.parse_args()
    data = args.pbf.read_bytes()
    styles = extract(data)["styles"]
    output = (
        "// Generated by scaffold/tools/generate_amap_surface_data.py.\n"
        f"// Source SHA256: {hashlib.sha256(data).hexdigest()}.\n"
        "// Do not edit manually.\n\n"
        + emit_surfaces(styles) + "\n\n"
        + emit_buildings(styles) + "\n")
    args.output.write_text(output)


if __name__ == "__main__":
    main()
