#include "TileFrameDebugLogFormatter.h"

#include <cstdio>

namespace earth_engine {

std::array<char, 2048> TileFrameDebugLogFormatter::updateDetail(
    const TileUpdateDebugLogInput& input) {
    std::array<char, 2048> detail{};
    std::snprintf(
        detail.data(),
        detail.size(),
        "render=%zu load=%zu selector=%.2f selTrav=%.2f selDetail=%d selVis=%.2f selMetric=%.2f selPolicy=%.2f selRefine=%.2f selOv=%.2f selDec=%.2f selMat=%.2f selMatCalls=%d selMatChanged=%d selMatRetry=%d selMatFast=%d selCommit=%.2f selPlan=%.2f selReq=%.2f prefetch=%.2f prefetchBase=%.2f prefetchFill=%.2f prefRender=%.2f prefRenderUpdate=%.2f prefRenderAction=%.2f prefetchVisible=%.2f prefetchLoad=%.2f prefetchAdvance=%.2f prefetchMap=%.2f prefetchEarlyMap=%.2f prefEarly=%d/%d/%d prefEarlyEx=%d request=%.2f reqClass=%zu/%zu/%zu reqIssued=%zu/%zu/%zu reqUpCap=%zu reqMotion=%zu terrainUpload=%.2f gpuDrain=%.2f rasterUpload=%.2f rasterPick=%.2f rasterFallback=%.2f rasterSnapshot=%.2f rasterIssue=%.2f rasterQueue=%.2f rasterTex=%.2f rasterFinalize=%.2f rasterBook=%.2f cache=%zu pending=%zu memTotalKB=%lld memContentKB=%lld memImageryKB=%lld rsrc=%d activeSets=%d fallbacks=%d srcInflight=%d srcWaiters=%d pendUp=%d visited=%d culled=%d culledVisited=%d fog=%d occluded=%d occWait=%d kicked=%d notReady=%d reused=%d reuseMode=%d reuseReject=%d prefVis=%d prefLoad=%d prefAdv=%d prefMap=%d prefRenderTiles=%d prefRenderAuth=%d prefRenderReuse=%d rasterUploads=%d rasterMapped=%d rasterMax=%.2f rasterMaxSize=%dx%d interaction=%d smoothing=%d",
        input.renderTileCount,
        input.loadRequestCount,
        input.selectorMs,
        input.selectorTraversalMs,
        input.selectorDetailedTimings ? 1 : 0,
        input.selectorVisitVisibilityMs,
        input.selectorVisitInputMetricsMs,
        input.selectorVisitPolicyMs,
        input.selectorRefineMs,
        input.selectorRefineOverlayMs,
        input.selectorRefineDecisionMs,
        input.selectorRefineMaterializeMs,
        input.selectorRefineMaterializeCalls,
        input.selectorRefineMaterializeChanged,
        input.selectorRefineMaterializeRetry,
        input.selectorRefineMaterializeFastPath,
        input.selectorRefineCommitMs,
        input.selectorRenderPlanMs,
        input.selectorRequestPlanningMs,
        input.prefetchMs,
        input.prefetchBaseMs,
        input.prefetchFillMs,
        input.prefetchRenderPlanMs,
        input.prefetchRenderPlanUpdateMs,
        input.prefetchRenderPlanActionMs,
        input.prefetchVisibleMs,
        input.prefetchLoadQueueMs,
        input.prefetchAdvanceMs,
        input.prefetchMapMs,
        input.prefetchEarlyMapMs,
        input.prefetchEarlyMapCount,
        input.prefetchVisibleEarlyMapCount,
        input.prefetchLoadQueueEarlyMapCount,
        input.prefetchEarlyMapBudgetExhausted ? 1 : 0,
        input.requestMs,
        input.requestClassifiedContent,
        input.requestClassifiedTerrainAvailabilityUpsample,
        input.requestClassifiedRasterDetailUpsample,
        input.requestIssuedContent,
        input.requestIssuedTerrainAvailabilityUpsample,
        input.requestIssuedRasterDetailUpsample,
        input.requestUpsampleWorkerCapacity,
        input.requestMotionDeferred,
        input.terrainUploadMs,
        input.gpuUploadDrainMs,
        input.rasterUploadMs,
        input.rasterSelectTaskMs,
        input.rasterSourceFallbackMs,
        input.rasterSourceSnapshotMs,
        input.rasterSourceIssueMs,
        input.rasterUploadQueueSelectMs,
        input.rasterUploadTextureMs,
        input.rasterTileFinalizeMs,
        input.rasterBookkeepingMs,
        input.terrainCacheSize,
        input.pendingRequestCount,
        static_cast<long long>(input.residentTotalBytes / 1024),
        static_cast<long long>(input.contentResidentBytes / 1024),
        static_cast<long long>(input.imageryTextureBytes / 1024),
        input.rasterSourceRequestsInFlight,
        input.rasterActiveMappedSourceSets,
        input.rasterPendingSourceFallbacks,
        input.rasterInFlightSourceTiles,
        input.rasterInFlightSourceWaiters,
        input.rasterPendingUploads,
        input.selectionCounters.visited,
        input.selectionCounters.culled,
        input.selectionCounters.culledVisited,
        input.selectionCounters.fogCulled,
        input.selectionCounters.occluded,
        input.selectionCounters.waitingForOcclusionResults,
        input.selectionCounters.kicked,
        input.selectionCounters.notYetRenderable,
        input.reusedSelection ? 1 : 0,
        static_cast<int>(input.reuseMode),
        static_cast<int>(input.reuseRejectReason),
        input.prefetchVisibleTiles,
        input.prefetchLoadQueueTiles,
        input.prefetchAdvanceCount,
        input.prefetchMapCount,
        input.prefetchRenderPlanTiles,
        input.prefetchRenderPlanAuthoritativeUpdates,
        input.prefetchRenderPlanStableReuses,
        input.rasterUploadsProcessed,
        input.rasterMappedUploadsProcessed,
        input.rasterUploadMaxMs,
        input.rasterUploadMaxWidth,
        input.rasterUploadMaxHeight,
        input.interactionActive ? 1 : 0,
        input.resourceSmoothingActive ? 1 : 0);
    return detail;
}

std::array<char, 512> TileFrameDebugLogFormatter::updateTailDetail(
    const TileUpdateDebugLogInput& input) {
    std::array<char, 512> detail{};
    std::snprintf(
        detail.data(),
        detail.size(),
        "prefEarly=%d/%d/%d prefEarlyEx=%d prefVis=%d prefLoad=%d prefAdv=%d prefMap=%d prefRenderTiles=%d prefRenderAuth=%d prefRenderReuse=%d rasterUploads=%d rasterMapped=%d rasterMax=%.2f rasterMaxSize=%dx%d interaction=%d smoothing=%d",
        input.prefetchEarlyMapCount,
        input.prefetchVisibleEarlyMapCount,
        input.prefetchLoadQueueEarlyMapCount,
        input.prefetchEarlyMapBudgetExhausted ? 1 : 0,
        input.prefetchVisibleTiles,
        input.prefetchLoadQueueTiles,
        input.prefetchAdvanceCount,
        input.prefetchMapCount,
        input.prefetchRenderPlanTiles,
        input.prefetchRenderPlanAuthoritativeUpdates,
        input.prefetchRenderPlanStableReuses,
        input.rasterUploadsProcessed,
        input.rasterMappedUploadsProcessed,
        input.rasterUploadMaxMs,
        input.rasterUploadMaxWidth,
        input.rasterUploadMaxHeight,
        input.interactionActive ? 1 : 0,
        input.resourceSmoothingActive ? 1 : 0);
    return detail;
}

std::array<char, 1024> TileFrameDebugLogFormatter::renderBuildDetail(
    const TileRenderDebugLogInput& input) {
    std::array<char, 1024> detail{};
    std::snprintf(
        detail.data(),
        detail.size(),
        "selected=%.2f fade=%.2f detach=%.2f trim=%.2f eligible=%.2f bytes=%.2f unload=%.2f selectedTiles=%zu fadeTiles=%zu entries=%d selectedEntries=%d fadeEntries=%d ensured=%d cmds=%zu selectedCmds=%d fadeCmds=%d missed=%d selectedMissed=%d fadeMissed=%d missingSelected=%d missingRender=%d deferred=%d selectedDeferred=%d fadeDeferred=%d interaction=%d smoothing=%d prepSync=%d prepDeferred=%d fallback=%d",
        input.selectedBuildMs,
        input.fadeBuildMs,
        input.maintenanceTimings.detachInactiveMs,
        input.maintenanceTimings.trimRasterMs,
        input.maintenanceTimings.eligibilityMs,
        input.maintenanceTimings.cacheBytesMs,
        input.maintenanceTimings.unloadMs,
        input.selectedTileCount,
        input.fadingTileCount,
        input.renderStats.plannedEntries,
        input.selectedRenderStats.plannedEntries,
        input.fadingRenderStats.plannedEntries,
        input.renderStats.ensuredTiles,
        input.commandCount,
        input.selectedRenderStats.drawAttempts,
        input.fadingRenderStats.drawAttempts,
        input.renderStats.missedDrawEntries,
        input.selectedRenderStats.missedDrawEntries,
        input.fadingRenderStats.missedDrawEntries,
        input.renderStats.missingSelectedTiles,
        input.renderStats.missingRenderTiles,
        input.renderStats.deferredEntries,
        input.selectedRenderStats.deferredEntries,
        input.fadingRenderStats.deferredEntries,
        input.interactionActive ? 1 : 0,
        input.resourceSmoothingActive ? 1 : 0,
        input.synchronousRenderPrepCount,
        input.deferredRenderPrepCount,
        input.ancestorFallbackDrawCount);
    return detail;
}

} // namespace earth_engine
